version: "3.3"
services:
  vote:
    build: ./app
    depends_on:
      - db
    ports: 
      - "80:80"
    networks: 
      - network-backend
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      APP_DB_USER: docker
      APP_DB_PASS: docker
      APP_DB_NAME: docker
    depends_on:
      - result
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks: 
      - network-backend

volumes:
    postgres_data:

networks:
  network-backend:
      driver: bridge